// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as NativeBase from "native-base";

function s(prim) {
  return prim;
}

function Component(Props) {
  return React.createElement(NativeBase.Box, {
              mt: "10",
              background: "primary.700",
              w: "40",
              h: "20",
              alignItems: "center",
              justifyContent: "center",
              children: null,
              _android: {
                m: "3"
              }
            }, React.createElement(NativeBase.Text, {
                  color: "black",
                  fontWeight: "bold",
                  children: "Hey"
                }), React.createElement(NativeBase.Input, {
                  size: "xl"
                }));
}

var make = Component;

export {
  s ,
  make ,
}
/* react Not a pure module */
