// Generated by ReScript, PLEASE EDIT WITH CARE

import * as $$Text from "./Text.bs.js";
import * as React from "react";
import * as NativeBase from "native-base";
import * as ReactNative from "react-native";

function s(prim) {
  return prim;
}

function Component(Props) {
  return React.createElement(NativeBase.Box, {
              children: null,
              m: "10",
              background: "primary"
            }, React.createElement(ReactNative.Text, {
                  children: "Hey"
                }), React.createElement((function (prim) {
                    return NativeBase.Text(prim);
                  }), $$Text.makeProps(undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "white", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, "Hey", undefined)), React.createElement(NativeBase.Box, {
                  width: "100",
                  height: "200"
                }));
}

var make = Component;

export {
  s ,
  make ,
}
/* react Not a pure module */
