// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Caml_option from "rescript/lib/es6/caml_option.js";

function makeProps(prim0, prim1, prim2, prim3, prim4, prim5, prim6, prim7, prim8, prim9, prim10, prim11, prim12, prim13, prim14, prim15, prim16, prim17, prim18, prim19, prim20, prim21, prim22, prim23, prim24, prim25, prim26, prim27, prim28, prim29, prim30, prim31, prim32, prim33, prim34, prim35, prim36, prim37, prim38, prim39, prim40, prim41, prim42, prim43, prim44, prim45, prim46, prim47, prim48, prim49, prim50, prim51, prim52, prim53, prim54, prim55, prim56, prim57, prim58, prim59, prim60, prim61, prim62, prim63, prim64, prim65, prim66, prim67, prim68, prim69, prim70, prim71, prim72, prim73, prim74, prim75, prim76, prim77, prim78, prim79, prim80, prim81, prim82, prim83, prim84, prim85, prim86, prim87, prim88, prim89, prim90, prim91, prim92, prim93, prim94, prim95, prim96, prim97, prim98, prim99, prim100, prim101, prim102, prim103, prim104, prim105, prim106, prim107, prim108, prim109, prim110, prim111, prim112, prim113, prim114, prim115, prim116, prim117, prim118, prim119, prim120, prim121) {
  var tmp = {};
  if (prim0 !== undefined) {
    tmp.m = Caml_option.valFromOption(prim0);
  }
  if (prim1 !== undefined) {
    tmp.margin = Caml_option.valFromOption(prim1);
  }
  if (prim2 !== undefined) {
    tmp.mt = Caml_option.valFromOption(prim2);
  }
  if (prim3 !== undefined) {
    tmp.marginTop = Caml_option.valFromOption(prim3);
  }
  if (prim4 !== undefined) {
    tmp.mr = Caml_option.valFromOption(prim4);
  }
  if (prim5 !== undefined) {
    tmp.marginRight = Caml_option.valFromOption(prim5);
  }
  if (prim6 !== undefined) {
    tmp.mb = Caml_option.valFromOption(prim6);
  }
  if (prim7 !== undefined) {
    tmp.marginBottom = Caml_option.valFromOption(prim7);
  }
  if (prim8 !== undefined) {
    tmp.ml = Caml_option.valFromOption(prim8);
  }
  if (prim9 !== undefined) {
    tmp.marginLeft = Caml_option.valFromOption(prim9);
  }
  if (prim10 !== undefined) {
    tmp.mx = Caml_option.valFromOption(prim10);
  }
  if (prim11 !== undefined) {
    tmp.my = Caml_option.valFromOption(prim11);
  }
  if (prim12 !== undefined) {
    tmp.p = Caml_option.valFromOption(prim12);
  }
  if (prim13 !== undefined) {
    tmp.padding = Caml_option.valFromOption(prim13);
  }
  if (prim14 !== undefined) {
    tmp.pt = Caml_option.valFromOption(prim14);
  }
  if (prim15 !== undefined) {
    tmp.paddingTop = Caml_option.valFromOption(prim15);
  }
  if (prim16 !== undefined) {
    tmp.pr = Caml_option.valFromOption(prim16);
  }
  if (prim17 !== undefined) {
    tmp.paddingRight = Caml_option.valFromOption(prim17);
  }
  if (prim18 !== undefined) {
    tmp.pb = Caml_option.valFromOption(prim18);
  }
  if (prim19 !== undefined) {
    tmp.paddingBottom = Caml_option.valFromOption(prim19);
  }
  if (prim20 !== undefined) {
    tmp.pl = Caml_option.valFromOption(prim20);
  }
  if (prim21 !== undefined) {
    tmp.paddingLeft = Caml_option.valFromOption(prim21);
  }
  if (prim22 !== undefined) {
    tmp.px = Caml_option.valFromOption(prim22);
  }
  if (prim23 !== undefined) {
    tmp.py = Caml_option.valFromOption(prim23);
  }
  if (prim24 !== undefined) {
    tmp.color = Caml_option.valFromOption(prim24);
  }
  if (prim25 !== undefined) {
    tmp.bg = Caml_option.valFromOption(prim25);
  }
  if (prim26 !== undefined) {
    tmp.background = Caml_option.valFromOption(prim26);
  }
  if (prim27 !== undefined) {
    tmp.bgColor = Caml_option.valFromOption(prim27);
  }
  if (prim28 !== undefined) {
    tmp.opacity = Caml_option.valFromOption(prim28);
  }
  if (prim29 !== undefined) {
    tmp.fontFamily = Caml_option.valFromOption(prim29);
  }
  if (prim30 !== undefined) {
    tmp.fontSize = Caml_option.valFromOption(prim30);
  }
  if (prim31 !== undefined) {
    tmp.fontWeight = Caml_option.valFromOption(prim31);
  }
  if (prim32 !== undefined) {
    tmp.lineHeight = Caml_option.valFromOption(prim32);
  }
  if (prim33 !== undefined) {
    tmp.letterSpacing = Caml_option.valFromOption(prim33);
  }
  if (prim34 !== undefined) {
    tmp.textAlign = Caml_option.valFromOption(prim34);
  }
  if (prim35 !== undefined) {
    tmp.fontStyle = Caml_option.valFromOption(prim35);
  }
  if (prim36 !== undefined) {
    tmp.textTransform = Caml_option.valFromOption(prim36);
  }
  if (prim37 !== undefined) {
    tmp.textDecoration = Caml_option.valFromOption(prim37);
  }
  if (prim38 !== undefined) {
    tmp.w = Caml_option.valFromOption(prim38);
  }
  if (prim39 !== undefined) {
    tmp.width = Caml_option.valFromOption(prim39);
  }
  if (prim40 !== undefined) {
    tmp.h = Caml_option.valFromOption(prim40);
  }
  if (prim41 !== undefined) {
    tmp.height = Caml_option.valFromOption(prim41);
  }
  if (prim42 !== undefined) {
    tmp.minW = Caml_option.valFromOption(prim42);
  }
  if (prim43 !== undefined) {
    tmp.minWidth = Caml_option.valFromOption(prim43);
  }
  if (prim44 !== undefined) {
    tmp.maxW = Caml_option.valFromOption(prim44);
  }
  if (prim45 !== undefined) {
    tmp.maxWidth = Caml_option.valFromOption(prim45);
  }
  if (prim46 !== undefined) {
    tmp.minH = Caml_option.valFromOption(prim46);
  }
  if (prim47 !== undefined) {
    tmp.minHeight = Caml_option.valFromOption(prim47);
  }
  if (prim48 !== undefined) {
    tmp.maxH = Caml_option.valFromOption(prim48);
  }
  if (prim49 !== undefined) {
    tmp.maxHeight = Caml_option.valFromOption(prim49);
  }
  if (prim50 !== undefined) {
    tmp.d = Caml_option.valFromOption(prim50);
  }
  if (prim51 !== undefined) {
    tmp.display = Caml_option.valFromOption(prim51);
  }
  if (prim52 !== undefined) {
    tmp.boxSize = Caml_option.valFromOption(prim52);
  }
  if (prim53 !== undefined) {
    tmp.verticalAlign = Caml_option.valFromOption(prim53);
  }
  if (prim54 !== undefined) {
    tmp.overflow = Caml_option.valFromOption(prim54);
  }
  if (prim55 !== undefined) {
    tmp.overflowX = Caml_option.valFromOption(prim55);
  }
  if (prim56 !== undefined) {
    tmp.overflowY = Caml_option.valFromOption(prim56);
  }
  if (prim57 !== undefined) {
    tmp.alignItems = Caml_option.valFromOption(prim57);
  }
  if (prim58 !== undefined) {
    tmp.align = Caml_option.valFromOption(prim58);
  }
  if (prim59 !== undefined) {
    tmp.alignContent = Caml_option.valFromOption(prim59);
  }
  if (prim60 !== undefined) {
    tmp.justifyItems = Caml_option.valFromOption(prim60);
  }
  if (prim61 !== undefined) {
    tmp.justifyContent = Caml_option.valFromOption(prim61);
  }
  if (prim62 !== undefined) {
    tmp.justify = Caml_option.valFromOption(prim62);
  }
  if (prim63 !== undefined) {
    tmp.flexWrap = Caml_option.valFromOption(prim63);
  }
  if (prim64 !== undefined) {
    tmp.wrap = Caml_option.valFromOption(prim64);
  }
  if (prim65 !== undefined) {
    tmp.flexDirection = Caml_option.valFromOption(prim65);
  }
  if (prim66 !== undefined) {
    tmp.flexDir = Caml_option.valFromOption(prim66);
  }
  if (prim67 !== undefined) {
    tmp.direction = Caml_option.valFromOption(prim67);
  }
  if (prim68 !== undefined) {
    tmp.flex = Caml_option.valFromOption(prim68);
  }
  if (prim69 !== undefined) {
    tmp.flexGrow = Caml_option.valFromOption(prim69);
  }
  if (prim70 !== undefined) {
    tmp.flexShrink = Caml_option.valFromOption(prim70);
  }
  if (prim71 !== undefined) {
    tmp.flexBasis = Caml_option.valFromOption(prim71);
  }
  if (prim72 !== undefined) {
    tmp.justifySelf = Caml_option.valFromOption(prim72);
  }
  if (prim73 !== undefined) {
    tmp.alignSelf = Caml_option.valFromOption(prim73);
  }
  if (prim74 !== undefined) {
    tmp.order = Caml_option.valFromOption(prim74);
  }
  if (prim75 !== undefined) {
    tmp.borderWidth = Caml_option.valFromOption(prim75);
  }
  if (prim76 !== undefined) {
    tmp.borderStyle = Caml_option.valFromOption(prim76);
  }
  if (prim77 !== undefined) {
    tmp.borderColor = Caml_option.valFromOption(prim77);
  }
  if (prim78 !== undefined) {
    tmp.borderTop = Caml_option.valFromOption(prim78);
  }
  if (prim79 !== undefined) {
    tmp.borderTopWidth = Caml_option.valFromOption(prim79);
  }
  if (prim80 !== undefined) {
    tmp.borderTopStyle = Caml_option.valFromOption(prim80);
  }
  if (prim81 !== undefined) {
    tmp.borderTopColor = Caml_option.valFromOption(prim81);
  }
  if (prim82 !== undefined) {
    tmp.borderRight = Caml_option.valFromOption(prim82);
  }
  if (prim83 !== undefined) {
    tmp.borderRightWidth = Caml_option.valFromOption(prim83);
  }
  if (prim84 !== undefined) {
    tmp.borderRightStyle = Caml_option.valFromOption(prim84);
  }
  if (prim85 !== undefined) {
    tmp.borderRightColor = Caml_option.valFromOption(prim85);
  }
  if (prim86 !== undefined) {
    tmp.borderBottom = Caml_option.valFromOption(prim86);
  }
  if (prim87 !== undefined) {
    tmp.borderBottomWidth = Caml_option.valFromOption(prim87);
  }
  if (prim88 !== undefined) {
    tmp.borderBottomStyle = Caml_option.valFromOption(prim88);
  }
  if (prim89 !== undefined) {
    tmp.borderBottomColor = Caml_option.valFromOption(prim89);
  }
  if (prim90 !== undefined) {
    tmp.borderLeft = Caml_option.valFromOption(prim90);
  }
  if (prim91 !== undefined) {
    tmp.borderLeftWidth = Caml_option.valFromOption(prim91);
  }
  if (prim92 !== undefined) {
    tmp.borderLeftStyle = Caml_option.valFromOption(prim92);
  }
  if (prim93 !== undefined) {
    tmp.borderLeftColor = Caml_option.valFromOption(prim93);
  }
  if (prim94 !== undefined) {
    tmp.borderRadius = Caml_option.valFromOption(prim94);
  }
  if (prim95 !== undefined) {
    tmp.rounded = Caml_option.valFromOption(prim95);
  }
  if (prim96 !== undefined) {
    tmp.borderTopLeftRadius = Caml_option.valFromOption(prim96);
  }
  if (prim97 !== undefined) {
    tmp.roundedTopLeft = Caml_option.valFromOption(prim97);
  }
  if (prim98 !== undefined) {
    tmp.borderTopRightRadius = Caml_option.valFromOption(prim98);
  }
  if (prim99 !== undefined) {
    tmp.roundedTopRight = Caml_option.valFromOption(prim99);
  }
  if (prim100 !== undefined) {
    tmp.borderBottomRightRadius = Caml_option.valFromOption(prim100);
  }
  if (prim101 !== undefined) {
    tmp.roundedBottomRight = Caml_option.valFromOption(prim101);
  }
  if (prim102 !== undefined) {
    tmp.borderBottomLeftRadius = Caml_option.valFromOption(prim102);
  }
  if (prim103 !== undefined) {
    tmp.roundedBottomLeft = Caml_option.valFromOption(prim103);
  }
  if (prim104 !== undefined) {
    tmp.borderTopRadius = Caml_option.valFromOption(prim104);
  }
  if (prim105 !== undefined) {
    tmp.roundedTop = Caml_option.valFromOption(prim105);
  }
  if (prim106 !== undefined) {
    tmp.borderRightRadius = Caml_option.valFromOption(prim106);
  }
  if (prim107 !== undefined) {
    tmp.roundedRight = Caml_option.valFromOption(prim107);
  }
  if (prim108 !== undefined) {
    tmp.borderBottomRadius = Caml_option.valFromOption(prim108);
  }
  if (prim109 !== undefined) {
    tmp.roundedBottom = Caml_option.valFromOption(prim109);
  }
  if (prim110 !== undefined) {
    tmp.borderLeftRadius = Caml_option.valFromOption(prim110);
  }
  if (prim111 !== undefined) {
    tmp.roundedLeft = Caml_option.valFromOption(prim111);
  }
  if (prim112 !== undefined) {
    tmp.pos = Caml_option.valFromOption(prim112);
  }
  if (prim113 !== undefined) {
    tmp.position = Caml_option.valFromOption(prim113);
  }
  if (prim114 !== undefined) {
    tmp.zIndex = Caml_option.valFromOption(prim114);
  }
  if (prim115 !== undefined) {
    tmp.top = Caml_option.valFromOption(prim115);
  }
  if (prim116 !== undefined) {
    tmp.right = Caml_option.valFromOption(prim116);
  }
  if (prim117 !== undefined) {
    tmp.bottom = Caml_option.valFromOption(prim117);
  }
  if (prim118 !== undefined) {
    tmp.left = Caml_option.valFromOption(prim118);
  }
  if (prim119 !== undefined) {
    tmp.shadow = Caml_option.valFromOption(prim119);
  }
  if (prim120 !== undefined) {
    tmp.children = Caml_option.valFromOption(prim120);
  }
  return tmp;
}

var Binding = {
  makeProps: makeProps
};

export {
  Binding ,
  makeProps ,
}
/* No side effect */
