module Binding = {
  open ReactNative

  @module("native-base") @react.component
  external make: (
    //NativeBase props
    ~size: [#lg | #md | #sm | #xs]=?,
    ~colorScheme: [
      | #rose
      | #pink
      | #fuchsia
      | #purple
      | #violet
      | #indigo
      | #blue
      | #lightBlue
      | #darkBlue
      | #cyan
      | #teal
      | #emerald
      | #green
      | #lime
      | #yellow
      | #amber
      | #orange
      | #red
      | #warmGray
      | #trueGray
      | #gray
      | #coolGray
      | #blueGray
      | #dark
      | #text
      | #danger
      | #error
      | #success
      | #warning
      | #muted
      | #primary
      | #info
      | #secondary
      | #light
      | #tertiary
    ]=?,
    ~icon: React.element=?,
    ~variant: [#ghost | #outline | #solid | #subtle | #link | #unstyled]=?,
    // Utilitary props
    ~m: string=?,
    ~margin: string=?,
    ~mt: string=?,
    ~marginTop: string=?,
    ~mr: string=?,
    ~marginRight: string=?,
    ~mb: string=?,
    ~marginBottom: string=?,
    ~ml: string=?,
    ~marginLeft: string=?,
    ~mx: string=?,
    ~my: string=?,
    ~p: string=?,
    ~padding: string=?,
    ~pt: string=?,
    ~paddingTop: string=?,
    ~pr: string=?,
    ~paddingRight: string=?,
    ~pb: string=?,
    ~paddingBottom: string=?,
    ~pl: string=?,
    ~paddingLeft: string=?,
    ~px: string=?,
    ~py: string=?,
    ~color: string=?,
    ~bg: string=?,
    ~background: string=?,
    ~bgColor: string=?,
    ~opacity: string=?,
    ~fontFamily: string=?,
    ~fontSize: string=?,
    ~fontWeight: string=?,
    ~lineHeight: string=?,
    ~letterSpacing: string=?,
    ~textAlign: string=?,
    ~fontStyle: string=?,
    ~textTransform: string=?,
    ~textDecoration: string=?,
    ~w: string=?,
    ~width: string=?,
    ~h: string=?,
    ~height: string=?,
    ~minW: string=?,
    ~minWidth: string=?,
    ~maxW: string=?,
    ~maxWidth: string=?,
    ~minH: string=?,
    ~minHeight: string=?,
    ~maxH: string=?,
    ~maxHeight: string=?,
    ~d: string=?,
    ~display: string=?,
    ~boxSize: string=?,
    ~verticalAlign: string=?,
    ~overflow: string=?,
    ~overflowX: string=?,
    ~overflowY: string=?,
    ~alignItems: string=?,
    ~align: string=?,
    ~alignContent: string=?,
    ~justifyItems: string=?,
    ~justifyContent: string=?,
    ~justify: string=?,
    ~flexWrap: string=?,
    ~wrap: string=?,
    ~flexDirection: string=?,
    ~flexDir: string=?,
    ~direction: string=?,
    ~flex: string=?,
    ~flexGrow: string=?,
    ~flexShrink: string=?,
    ~flexBasis: string=?,
    ~justifySelf: string=?,
    ~alignSelf: string=?,
    ~order: string=?,
    ~borderWidth: string=?,
    ~borderStyle: string=?,
    ~borderColor: string=?,
    ~borderTop: string=?,
    ~borderTopWidth: string=?,
    ~borderTopStyle: string=?,
    ~borderTopColor: string=?,
    ~borderRight: string=?,
    ~borderRightWidth: string=?,
    ~borderRightStyle: string=?,
    ~borderRightColor: string=?,
    ~borderBottom: string=?,
    ~borderBottomWidth: string=?,
    ~borderBottomStyle: string=?,
    ~borderBottomColor: string=?,
    ~borderLeft: string=?,
    ~borderLeftWidth: string=?,
    ~borderLeftStyle: string=?,
    ~borderLeftColor: string=?,
    ~borderRadius: string=?,
    ~rounded: string=?,
    ~borderTopLeftRadius: string=?,
    ~roundedTopLeft: string=?,
    ~borderTopRightRadius: string=?,
    ~roundedTopRight: string=?,
    ~borderBottomRightRadius: string=?,
    ~roundedBottomRight: string=?,
    ~borderBottomLeftRadius: string=?,
    ~roundedBottomLeft: string=?,
    ~borderTopRadius: string=?,
    ~roundedTop: string=?,
    ~borderRightRadius: string=?,
    ~roundedRight: string=?,
    ~borderBottomRadius: string=?,
    ~roundedBottom: string=?,
    ~borderLeftRadius: string=?,
    ~roundedLeft: string=?,
    ~pos: string=?,
    ~position: string=?,
    ~zIndex: string=?,
    ~top: string=?,
    ~right: string=?,
    ~bottom: string=?,
    ~left: string=?,
    ~shadow: string=?,
    // React props
    ~style: ReactNative.Style.t=?,
    // RN Button Options
    ~accessibilityActions: array<Accessibility.actionInfo>=?,
    ~accessibilityLabel: string=?,
    ~accessibilityState: Accessibility.state=?,
    ~accessible: bool=?,
    ~color: Color.t=?,
    ~disabled: bool=?,
    ~hasTVPreferredFocus: bool=?,
    ~nextFocusDown: int=?,
    ~nextFocusForward: int=?,
    ~nextFocusLeft: int=?,
    ~nextFocusRight: int=?,
    ~nextFocusUp: int=?,
    ~onAccessibilityAction: Accessibility.actionEvent => unit=?,
    ~onPress: Event.pressEvent => unit,
    ~testID: string=?,
    ~title: string=?,
    ~touchSoundDisabled: bool=?,
    // Platform props
    ~_ios: Utilitary.props=?,
    ~_android: Utilitary.props=?,
    ~_web: Utilitary.props=?,
  ) => React.element = "IconButton"
}
include Binding
